name         = "yulma"
description  = "A modern Zola theme made with Bulma"
homepage     = "https://github.com/Ystorian/yulma"
license      = "MIT"
min_version  = "0.16.0"
compile_sass = true
base_url     = "."

[extra]
site_title       = "Yulma"
debug            = true
site_description = "A modern Zola theme made with Bulma"
