name         = "yulma"
description  = "A modern Zola theme made with Bulma"
homepage     = "https://github.com/Ystorian/yulma"
license      = "MIT"
min_version  = "0.16.0"
compile_sass = true

[author]
name     = "Flavien Scheurer"
homepage = "https://github.com/Ystorian/yulma"

[original]
author = "Worble"
repo   = "https://github.com/Worble/Zulma"
